"""baseline: reflect existing schema

Revision ID: a9262bb8c004
Revises: 
Create Date: 2026-08-04 02:00:50.038768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9262bb8c004'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_cache',
    sa.Column('linkedin_url', sa.Text(), nullable=False),
    sa.Column('scraped_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_url')
    )
    op.create_index('linkedin_cache_scraped_at_idx', 'linkedin_cache', ['scraped_at'], unique=False)
    op.create_index('linkedin_cache_url_idx', 'linkedin_cache', ['linkedin_url'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), server_default='free', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_city', sa.Text(), nullable=True),
    sa.Column('address_postal_code', sa.Text(), nullable=True),
    sa.Column('address_country', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('work_authorization', sa.Text(), nullable=True),
    sa.Column('cv_photo_url', sa.Text(), nullable=True),
    sa.Column('cv_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_campaigns',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('delay_seconds', sa.Integer(), server_default='30', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('campaigns_status_idx', 'email_campaigns', ['status'], unique=False)
    op.create_index('campaigns_user_id_idx', 'email_campaigns', ['user_id'], unique=False)
    op.create_table('job_applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.Date(), server_default=sa.text('current_date'), nullable=False),
    sa.Column('status', sa.Text(), server_default='Applied', nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('applications_follow_up_idx', 'job_applications', ['follow_up_date'], unique=False)
    op.create_index('applications_status_idx', 'job_applications', ['status'], unique=False)
    op.create_index('applications_user_id_idx', 'job_applications', ['user_id'], unique=False)
    op.create_table('startup_hunt_companies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('company_domain', sa.Text(), nullable=True),
    sa.Column('company_website_url', sa.Text(), nullable=True),
    sa.Column('company_careers_url', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('company_size', sa.Text(), nullable=True),
    sa.Column('ai_relevance', sa.Text(), nullable=True),
    sa.Column('english_friendly', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('relocation_support', sa.Text(), nullable=True),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('startup_hunt_companies_name_idx', 'startup_hunt_companies', ['company_name'], unique=False)
    op.create_index('startup_hunt_companies_user_idx', 'startup_hunt_companies', ['user_id'], unique=False)
    op.create_table('startup_scout_companies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('what_they_do', sa.Text(), nullable=True),
    sa.Column('funding_stage', sa.Text(), nullable=True),
    sa.Column('size_range', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default='web_scrape', nullable=False),
    sa.Column('crawl_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("crawl_status in ('pending', 'crawling', 'enriched', 'partial', 'failed')", name='startup_scout_crawl_status_check'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('startup_scout_companies_status_idx', 'startup_scout_companies', ['crawl_status'], unique=False)
    op.create_index('startup_scout_companies_user_idx', 'startup_scout_companies', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), server_default='Custom', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('placeholders', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('templates_category_idx', 'templates', ['category'], unique=False)
    op.create_index('templates_user_id_idx', 'templates', ['user_id'], unique=False)
    op.create_table('email_recipients',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('recipients_campaign_id_idx', 'email_recipients', ['campaign_id'], unique=False)
    op.create_index('recipients_status_idx', 'email_recipients', ['status'], unique=False)
    op.create_table('job_search_applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('job_url_canonical', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('external_job_id', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('posted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('discovered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('application_status', sa.Text(), server_default='saved', nullable=False),
    sa.Column('tracker_application_id', sa.UUID(), nullable=True),
    sa.Column('citation_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('search_context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("application_status in ('saved', 'applied', 'skipped')", name='job_search_applications_status_check'),
    sa.ForeignKeyConstraint(['tracker_application_id'], ['job_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('job_search_applications_posted_idx', 'job_search_applications', [sa.text('posted_at DESC')], unique=False)
    op.create_index('job_search_applications_status_idx', 'job_search_applications', ['application_status'], unique=False)
    op.create_index('job_search_applications_tracker_idx', 'job_search_applications', ['tracker_application_id'], unique=False)
    op.create_index('job_search_applications_user_job_url_key', 'job_search_applications', ['user_id', 'job_url_canonical'], unique=True)
    op.create_table('startup_hunt_opportunities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('tracker_application_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('company_domain', sa.Text(), nullable=True),
    sa.Column('company_website_url', sa.Text(), nullable=True),
    sa.Column('company_careers_url', sa.Text(), nullable=True),
    sa.Column('role_title', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('direct_apply_url', sa.Text(), nullable=True),
    sa.Column('canonical_job_url', sa.Text(), nullable=True),
    sa.Column('portal_job_url', sa.Text(), nullable=True),
    sa.Column('posted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('discovered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opportunity_kind', sa.Text(), server_default='job', nullable=False),
    sa.Column('opportunity_status', sa.Text(), server_default='saved', nullable=False),
    sa.Column('score_total', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('score_labels', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('score_reasons', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('citation_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('company_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('search_context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("opportunity_kind in ('job', 'outreach_lead')", name='startup_hunt_opportunity_kind_check'),
    sa.CheckConstraint("opportunity_status in ('saved', 'applied', 'contacted', 'skipped')", name='startup_hunt_opportunity_status_check'),
    sa.ForeignKeyConstraint(['company_id'], ['startup_hunt_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracker_application_id'], ['job_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('startup_hunt_opportunities_company_idx', 'startup_hunt_opportunities', ['company_name'], unique=False)
    op.create_index('startup_hunt_opportunities_status_idx', 'startup_hunt_opportunities', ['opportunity_status'], unique=False)
    op.create_index('startup_hunt_opportunities_user_idx', 'startup_hunt_opportunities', ['user_id'], unique=False)
    op.create_table('startup_scout_contacts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['startup_scout_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('startup_scout_contacts_company_idx', 'startup_scout_contacts', ['company_id'], unique=False)
    op.create_index('startup_scout_contacts_user_idx', 'startup_scout_contacts', ['user_id'], unique=False)
    op.create_table('opportunity_artifacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.Text(), nullable=False),
    sa.Column('tool_used', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("artifact_type in ('resume_analysis', 'cover_letter', 'interview_prep')", name='opportunity_artifact_type_check'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['startup_hunt_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('opportunity_artifacts_opportunity_idx', 'opportunity_artifacts', ['opportunity_id'], unique=False)
    op.create_index('opportunity_artifacts_user_idx', 'opportunity_artifacts', ['user_id'], unique=False)
    op.create_table('startup_hunt_contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('contact_type', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('email_confidence', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('provider_chain', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['startup_hunt_companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['startup_hunt_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('startup_hunt_contacts_opportunity_idx', 'startup_hunt_contacts', ['opportunity_id'], unique=False)
    op.create_index('startup_hunt_contacts_user_idx', 'startup_hunt_contacts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('startup_hunt_contacts_user_idx', table_name='startup_hunt_contacts')
    op.drop_index('startup_hunt_contacts_opportunity_idx', table_name='startup_hunt_contacts')
    op.drop_table('startup_hunt_contacts')
    op.drop_index('opportunity_artifacts_user_idx', table_name='opportunity_artifacts')
    op.drop_index('opportunity_artifacts_opportunity_idx', table_name='opportunity_artifacts')
    op.drop_table('opportunity_artifacts')
    op.drop_index('startup_scout_contacts_user_idx', table_name='startup_scout_contacts')
    op.drop_index('startup_scout_contacts_company_idx', table_name='startup_scout_contacts')
    op.drop_table('startup_scout_contacts')
    op.drop_index('startup_hunt_opportunities_user_idx', table_name='startup_hunt_opportunities')
    op.drop_index('startup_hunt_opportunities_status_idx', table_name='startup_hunt_opportunities')
    op.drop_index('startup_hunt_opportunities_company_idx', table_name='startup_hunt_opportunities')
    op.drop_table('startup_hunt_opportunities')
    op.drop_index('job_search_applications_user_job_url_key', table_name='job_search_applications')
    op.drop_index('job_search_applications_tracker_idx', table_name='job_search_applications')
    op.drop_index('job_search_applications_status_idx', table_name='job_search_applications')
    op.drop_index('job_search_applications_posted_idx', table_name='job_search_applications')
    op.drop_table('job_search_applications')
    op.drop_index('recipients_status_idx', table_name='email_recipients')
    op.drop_index('recipients_campaign_id_idx', table_name='email_recipients')
    op.drop_table('email_recipients')
    op.drop_index('templates_user_id_idx', table_name='templates')
    op.drop_index('templates_category_idx', table_name='templates')
    op.drop_table('templates')
    op.drop_index('startup_scout_companies_user_idx', table_name='startup_scout_companies')
    op.drop_index('startup_scout_companies_status_idx', table_name='startup_scout_companies')
    op.drop_table('startup_scout_companies')
    op.drop_index('startup_hunt_companies_user_idx', table_name='startup_hunt_companies')
    op.drop_index('startup_hunt_companies_name_idx', table_name='startup_hunt_companies')
    op.drop_table('startup_hunt_companies')
    op.drop_index('applications_user_id_idx', table_name='job_applications')
    op.drop_index('applications_status_idx', table_name='job_applications')
    op.drop_index('applications_follow_up_idx', table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index('campaigns_user_id_idx', table_name='email_campaigns')
    op.drop_index('campaigns_status_idx', table_name='email_campaigns')
    op.drop_table('email_campaigns')
    op.drop_table('profiles')
    op.drop_index('linkedin_cache_url_idx', table_name='linkedin_cache')
    op.drop_index('linkedin_cache_scraped_at_idx', table_name='linkedin_cache')
    op.drop_table('linkedin_cache')
    # ### end Alembic commands ###
