"""add clerk_user_id and role to profiles

Revision ID: b8c8fffadcd0
Revises: ae83bb0194fa
Create Date: 2026-08-08 00:58:30.004176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c8fffadcd0'
down_revision: Union[str, None] = 'ae83bb0194fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('clerk_user_id', sa.Text(), nullable=False))
    op.add_column('profiles', sa.Column('role', sa.Text(), server_default='user', nullable=False))
    op.create_index(op.f('ix_profiles_clerk_user_id'), 'profiles', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_clerk_user_id'), table_name='profiles')
    op.drop_column('profiles', 'role')
    op.drop_column('profiles', 'clerk_user_id')
    # ### end Alembic commands ###
